services:
  - name: ia-dev
    type: web
    env: docker
    plan: free
    dockerfilePath: backend/src/InsuranceAnalytics.Api/Dockerfile
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Development
    autoDeploy: true

  - name: ia-prod
    type: web
    env: docker
    plan: free
    dockerfilePath: backend/src/InsuranceAnalytics.Api/Dockerfile
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
    autoDeploy: true

  - name: ia-uat
    type: web
    env: docker
    plan: free
    dockerfilePath: backend/src/InsuranceAnalytics.Api/Dockerfile
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Uat
    autoDeploy: true